Added basic signup validation for frontend
TDDD96-G11-BLHub/website pull request #12
Opened 2024-04-09 12:10 UTC by valdemarbang

- Checking first and lastname not empty or using blank spaces.
- Email is validated with regex, checking that a string exist like this string@string.string
- Password needs to be atleast 6 characters long for that extra spicy safety.

2024-04-09 16:39 UTC, Jacalz requested changes
Nice work. Just one suggestion similar to https://github.com/TDDD96-G11-BLHub/website/pull/13#discussion_r1557966366.

2024-04-09 16:39 UTC, Jacalz commented on src/components/SignUp.tsx
> +    }
You can get rid of the shitty way like this :)
```suggestion
    if (firstname.trim() === "") { // trim removes whitespace
      setFirstNameError("First name is required");
      return;
    }

    if (lastname.trim() === "") {
      setLastNameError("Last name is required");
      return;
    }

    if (!/^[\w-]+(\.[\w-]+)*@([\w-]+\.)+[a-zA-Z]{2,7}$/.test(email)) {
      setEmailError("Please enter a valid email address");
      return;
    }

    if (password.length < 6) {
      setPasswordError("Password must be at least 6 characters long");
      return;
    }
```

2024-04-10 06:46 UTC, Jacalz approved these changes

2024-04-10 06:47 UTC, Jacalz commented on src/components/SignUp.tsx
> +    }
Makes sense. Thanks for explaning

2024-04-10 06:49 UTC, emilloof approved these changes

2024-04-10 08:14 UTC, merged