Added a login page and component
TDDD96-G11-BLHub/website pull request #13
Opened 2024-04-09 14:03 UTC by valdemarbang

2024-04-09 16:34 UTC, Jacalz requested changes
Wow. Nice work. I just left two minor suggestions inline :)

2024-04-09 16:34 UTC, Jacalz commented on src/components/Login.tsx
> +    let hasErrors = false; // shitty way of doing this, but it works
How about just returning each time you do `hasErrors = true` instead?

2024-04-09 16:34 UTC, Jacalz commented on src/components/Login.tsx
> +    else {
```suggestion
    } else { // sucessful login
```

2024-04-10 06:46 UTC, Jacalz commented on src/components/Login.tsx
> +    let hasErrors = false; // shitty way of doing this, but it works
Good point. Thanks for explaining

2024-04-10 06:46 UTC, Jacalz submitted a review, later dismissed

2024-04-10 06:49 UTC, emilloof approved these changes

2024-04-10 08:14 UTC, Jacalz approved these changes

2024-04-10 08:17 UTC, Jacalz approved these changes

2024-04-10 08:18 UTC, emilloof approved these changes

2024-04-10 08:18 UTC, merged